### ISSUE TITLE
migrate 10x pipeline to LSF

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/rhumba#2]
cellranger 3.0.2 can use lsf as a jobmanager. I imagine this would speed things up quite a bit.

``` bash
#!/usr/bin/env bash

#BSUB -J 10x_master
#BSUB -o log/10x_master.%J.%I.out
#BSUB -e log/10x_master.%J.%I.err

set -o nounset -o pipefail -o errexit -x

# module load cellranger/3.0.2

cellranger count \
    --id="10x_protease2" \
    --transcriptome=$REFDATA/refdata-cellranger-GRCh38-3.0.0 \
    --libraries="libraries.csv" \
    --feature-ref="features.csv" \
    --jobmode=lsf \
    --maxjobs=32 \
    --mempercore=32
```

Specific params can be set in `/cluster/software/modules-sw/cellranger/3.0.2/martian-cs/v3.2.0/jobmanagers/lsf.template`. I think you can copy this locally and give the file path to `--jobmode`. We'd need to set `-q rna` in the local one.

**Comment by kriemo** [comment]
The current snakemake 10x pipeline is already set up to work with lsf. https://github.com/rnabioco/rhumba/blob/b01bc109705b72b48cd30f5804a04489691923f7/scRNAseq/rules/10x_count.snake#L116

We've have been using local install of cellranger which is configured to run with LSF.
`/beevol/home/riemondy/src/cellranger-3.0.1/martian-cs/v3.1.0/jobmanagers/lsf.template`

It would probably be best to switch to using the modules version. I can update the README to provide instructions for using the modules version and setting up the appropriate lsf job template.
